--USER
INSERT INTO SPNT_USER VALUES('USR1', 'Daniel Lincango', 'flincangoups@gmail.com');
INSERT INTO SPNT_USER VALUES('USR2', 'Fernando Baquero', 'fbaquero92@gmail.com');

--STATE
INSERT INTO SPNT_TICKETCATALOGUE VALUES('OPN', 'Open', '1', 'STA');
INSERT INTO SPNT_TICKETCATALOGUE VALUES('ESC', 'Escalated', '1', 'STA');
INSERT INTO SPNT_TICKETCATALOGUE VALUES('CLO', 'Close', '1', 'STA');
-- PRIORITY
INSERT INTO SPNT_TICKETCATALOGUE VALUES('HIG', 'High', '1', 'PRI');
INSERT INTO SPNT_TICKETCATALOGUE VALUES('LOW', 'Low', '1', 'PRI');
--DEAL TYPE
INSERT INTO SPNT_TICKETCATALOGUE VALUES('MOB', 'Mobile Deal', '1', 'DEA');

-- TICKETS
INSERT INTO SPNT_TICKETS VALUES(NEXT VALUE FOR SPNS_TICKET, 'TICKET-1', 'Ticket aereo disponible 1', 'OPN', 'USR1', 'HIG', 'MOB', CURRENT_TIMESTAMP, '1');
INSERT INTO SPNT_TICKETS VALUES(NEXT VALUE FOR SPNS_TICKET, 'TICKET-2', 'Ticket aereo disponible 2', 'CLO', 'USR1', 'HIG', 'MOB', CURRENT_TIMESTAMP, '1');
INSERT INTO SPNT_TICKETS VALUES(NEXT VALUE FOR SPNS_TICKET, 'TICKET-3', 'Ticket aereo disponible 3', 'OPN', 'USR2', 'LOW', 'MOB', CURRENT_TIMESTAMP, '1');
INSERT INTO SPNT_TICKETS VALUES(NEXT VALUE FOR SPNS_TICKET, 'TICKET-4', 'Ticket aereo disponible 4', 'OPN', 'USR2', 'HIG', 'MOB', CURRENT_TIMESTAMP, '1');
INSERT INTO SPNT_TICKETS VALUES(NEXT VALUE FOR SPNS_TICKET, 'TICKET-5', 'Ticket aereo disponible 5', 'OPN', 'USR1', 'LOW', 'MOB', CURRENT_TIMESTAMP, '1');
INSERT INTO SPNT_TICKETS VALUES(NEXT VALUE FOR SPNS_TICKET, 'TICKET-6', 'Ticket aereo disponible 6', 'ESC', 'USR2', 'HIG', 'MOB', CURRENT_TIMESTAMP, '1');

